import { z } from "zod";

export const destinationSchema = z.object({
  name: z.string().min(2).max(100),
  slug: z.string().max(100).optional(),
  country: z.string().min(2).max(50),
  city: z.string().min(1).max(50),
  region: z.string().max(100).nullable().optional(),
  description: z.string().min(10).max(2000),
  price: z.coerce.number().min(0).optional(),
  duration: z.string().max(50).nullable().optional(),
  difficulty: z.string().max(50).nullable().optional(),
  groupSize: z.string().max(50).nullable().optional(),
  featured: z.coerce.boolean().optional(),
  trending: z.coerce.boolean().optional(),
  latitude: z.coerce.number().min(-90).max(90).nullable().optional(),
  longitude: z.coerce.number().min(-180).max(180).nullable().optional(),
  adventureScore: z.coerce.number().int().min(0).max(100).optional(),
  culturalScore: z.coerce.number().int().min(0).max(100).optional(),
  luxuryScore: z.coerce.number().int().min(0).max(100).optional(),
  familyScore: z.coerce.number().int().min(0).max(100).optional(),
  foodScore: z.coerce.number().int().min(0).max(100).optional(),
  hiddenGemScore: z.coerce.number().int().min(0).max(100).optional(),
  bestMonths: z.array(z.string().max(30)).max(12).optional(),
  travelStyles: z.array(z.string().max(50)).max(10).optional(),
  activities: z.array(z.string().max(100)).max(20).optional(),
  tags: z.array(z.string().max(40)).max(20).optional(),
  images: z.array(z.string().max(500)).max(15).optional(),
  status: z.enum(["DRAFT", "REVIEW", "PUBLISHED"]).optional(),
  metaTitle: z.string().max(70).nullable().optional(),
  metaDescription: z.string().max(160).nullable().optional(),
  ogImage: z.string().max(500).nullable().optional(),
  metadata: z.any().optional(),
});

export type DestinationInput = z.infer<typeof destinationSchema>;
