"use client";
import { motion } from 'framer-motion';
import Link from "next/link";
import { Compass } from "lucide-react";


const stagger = { visible: { transition: { staggerChildren: 0.05 } } };
const fadeUp = { hidden: { opacity: 0, y: 12 }, visible: { opacity: 1, y: 0, transition: { type: "spring" as const, stiffness: 80, damping: 20 } } };

export default function TermsView() {
  return (
    <div className="w-full min-h-[100dvh] bg-background text-night font-sans">
      <header className="w-full bg-surface border-b border-border/30 py-4 px-6">
        <div className="max-w-3xl mx-auto flex items-center gap-2">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-full bg-gold flex items-center justify-center text-night">
              <Compass className="w-3.5 h-3.5 stroke-[2.5]" />
            </div>
            <span className="font-display text-lg font-bold text-night">Travebie</span>
          </Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-16 space-y-8">
        <motion.h1 className="text-3xl font-display font-bold text-night"
          initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ type: "spring", stiffness: 80, damping: 20 }}>Terms of Service</motion.h1>
        <motion.p className="text-xs text-muted"
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.1, duration: 0.3 }}>Last updated: June 2026</motion.p>

        <motion.div className="space-y-8" variants={stagger} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-40px" }}>
          <motion.section variants={fadeUp} className="space-y-4">
            <h2 className="text-lg font-display font-semibold text-night">1. Acceptance of Terms</h2>
            <p className="text-sm text-charcoal leading-relaxed">
              By accessing or using Travebie ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.
            </p>
          </motion.section>

          <motion.section variants={fadeUp} className="space-y-4">
            <h2 className="text-lg font-display font-semibold text-night">2. Description of Service</h2>
            <p className="text-sm text-charcoal leading-relaxed">
              Travebie is an AI-powered travel discovery and planning platform focused on Indian destinations. The Platform provides destination recommendations, AI-generated itineraries, and travel information for informational purposes only.
            </p>
          </motion.section>

          <motion.section variants={fadeUp} className="space-y-4">
            <h2 className="text-lg font-display font-semibold text-night">3. User Responsibilities</h2>
            <p className="text-sm text-charcoal leading-relaxed">
              You agree to provide accurate information when using the Platform. You are responsible for maintaining the confidentiality of your account credentials. You agree not to misuse the Platform for any unlawful purpose.
            </p>
          </motion.section>

          <motion.section variants={fadeUp} className="space-y-4">
            <h2 className="text-lg font-display font-semibold text-night">4. AI-Generated Content</h2>
            <p className="text-sm text-charcoal leading-relaxed">
              Itineraries and recommendations generated by Travebie's AI are provided as suggestions only. They do not constitute professional travel advice. Always verify travel information independently, including visa requirements, safety conditions, and local regulations.
            </p>
          </motion.section>

          <motion.section variants={fadeUp} className="space-y-4">
            <h2 className="text-lg font-display font-semibold text-night">5. Limitation of Liability</h2>
            <p className="text-sm text-charcoal leading-relaxed">
              Travebie is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Platform, including but not limited to travel disruptions, booking decisions, or reliance on AI-generated content.
            </p>
          </motion.section>

          <motion.section variants={fadeUp} className="space-y-4">
            <h2 className="text-lg font-display font-semibold text-night">6. Changes to Terms</h2>
            <p className="text-sm text-charcoal leading-relaxed">
              We reserve the right to modify these terms at any time. Continued use of the Platform after changes constitutes acceptance of the updated terms.
            </p>
          </motion.section>
        </motion.div>

        <motion.div className="pt-6 border-t border-border/30"
          initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ delay: 0.2, duration: 0.4 }}>
          <p className="text-xs text-muted">
            For questions about these terms, contact us at{" "}
            <a href="mailto:tripzy.travell@gmail.com" className="text-gold underline">tripzy.travell@gmail.com</a>.
          </p>
        </motion.div>
      </main>
    </div>
  );
}
